[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
BUILD_TARGET = "./target/wasm32-unknown-unknown/release/"
CURRENT_CRATE = "NONE"
COMPILED_DIR = "artifacts"
CHECKSUM_DIR = "${COMPILED_DIR}/checksum"
DOCKER_IMAGE_VERSION = "v0.2"

[env.production]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "packages/*"

[tasks.deploy]
workspace = false
script = '''
SGX_MODE=SW cargo run --package shade-oracles-integration --bin deploy
'''

[tasks.cranky]
workspace = false
command = "cargo"
args = ["cranky", "--color", "always"]

[tasks.schemas]
workspace = false
script = '''
cargo run --package shade-oracles --bin schemas
'''

[tasks.release]
workspace = false
run_task = [{ name = ["build_with_args", "compress_with_args"] }]
dependencies = ["set_flags"]

[tasks.build_with_args]
private = true
workspace = false
command = "cargo"
args = ["build", "--release", "--package", "${@}", "--target", "wasm32-unknown-unknown"]

[tasks.compress_with_args]
private = true
workspace = false
script = '''
wasm-opt -Oz ${BUILD_TARGET}${@}.wasm -o ./${@}.wasm
echo $(md5sum ${@}.wasm | cut -f 1 -d " ") >> ${CHECKSUM_DIR}/${@}.txt
cat ./${@}.wasm | gzip -n -9 > ${COMPILED_DIR}/${@}.wasm.gz
rm ./${@}.wasm
'''

[tasks.set_flags]
workspace = false
private = true
script = '''
RUSTFLAGS='-C link-arg=-s'
'''

[tasks.build_all]
condition = { profiles = [ "production" ] }
env = { "CURRENT_CRATE" = "${CARGO_MAKE_CRATE_NAME}" }
run_task = [{ name = ["build", "compress"] }]
dependencies = ["set_flags"]

[tasks.build]
private = true
workspace = false
command = "cargo"
args = ["build", "--release", "--package", "${CURRENT_CRATE}", "--target", "wasm32-unknown-unknown"]

[tasks.compress]
private = true
workspace = false
script = '''
cd ../..
pwd
wasm-opt -Oz ${BUILD_TARGET}${CURRENT_CRATE}.wasm -o ./${CURRENT_CRATE}.wasm
echo $(md5sum ${CURRENT_CRATE}.wasm | cut -f 1 -d " ") >> ${CHECKSUM_DIR}/${CURRENT_CRATE}.txt
cat ./${CURRENT_CRATE}.wasm | gzip -n -9 > ${COMPILED_DIR}/${CURRENT_CRATE}.wasm.gz
rm ./${CURRENT_CRATE}.wasm
'''

[tasks.build-opt]
workspace = false
dependencies = ["schemas", "optimizoor", "compress-opt", "bundle"]

[tasks.build-fast]
workspace = false
dependencies = ["optimizoor", "compress-opt"]

[tasks.optimizoor]
workspace = false
command = "cargo"
args = ["cw-optimizoor"]

[tasks.compress-opt]
workspace = false
script = '''
for f in ${COMPILED_DIR}/*.wasm;
  do
        cat ./$f | gzip -n -9 > $f.gz
        rm ./$f
  done;
'''

[tasks.bundle]
workspace = false
script = '''
./bundle.sh ./artifacts
'''

[tasks.docs]
command = "cargo"
args = ["doc", "--no-deps", "--open"]

[tasks.test]
workspace = false
command = "cargo"
args = ["nextest", "run", "--package", "${@}"]

[tasks.test-all]
workspace = false
command = "cargo"
args = ["nextest", "run"]

[tasks.fmt]
workspace = false
command = "cargo"
args = ["fmt"]

[tasks.bacon-test]
workspace = false
command = "bacon"
args = ["test", "-s", "-w"]

[tasks.bacon]
workspace = false
command = "bacon"
args = ["-s", "-w"]

[tasks.clean]
workspace = false
dependencies = ["remove_compile_dir", "create_compile_dir", "create_checksum_dir"]

[tasks.remove_compile_dir]
private = true
workspace = false
command = "rm"
args = ["-r", "${COMPILED_DIR}", "-f"]

[tasks.create_compile_dir]
private = true
workspace = false
command = "mkdir"
args = ["${COMPILED_DIR}"]

[tasks.create_checksum_dir]
private = true
workspace = false
command = "mkdir"
args = ["${CHECKSUM_DIR}"]

# Docker support - can be run with `cargo make server start|connect|download
[tasks.server]
private = false
workspace = false
extend = "subcommand"
env = { "SUBCOMMAND_PREFIX" = "server" }

[tasks.subcommand]
private = true
workspace = false
script = '''
#!@duckscript

cm_run_task ${SUBCOMMAND_PREFIX}-${1}
'''


[tasks.server-download]
workspace = false
script = '''
docker pull securesecrets/sn-testnet:${DOCKER_IMAGE_VERSION}
'''

[tasks.server-start]
workspace = false
script = '''
docker run -it --rm \
   -p 26657:26657 -p 26656:26656 -p 1337:1337 \
   -v $$(pwd):/root/code --name shade-testnet securesecrets/sn-testnet:${DOCKER_IMAGE_VERSION}
'''

[tasks.server-connect]
workspace = false
script = '''
docker exec -it shade-testnet /bin/bash
'''