/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  router: RawContract;
}
export interface RawContract {
  address: string;
  code_hash: string;
}
export type ExecuteMsg = {
  set_rates: RawRateData[];
} | {
  remove_rates: string[];
} | {
  update_config: RawContract;
} | {
  update_rates: RateDataUpdate;
} | {
  set_status: boolean;
};
export type Decimal256 = string;
export type RateDataUpdate = {
  rates: [string, Decimal256][];
} | {
  config: [string, RateDataConfigUpdate][];
};
export interface RawRateData {
  initial_rate: Decimal256;
  key: string;
  max_change: Decimal256;
  permission: string;
  timeout: number;
}
export interface RateDataConfigUpdate {
  max_change?: Decimal256 | null;
  timeout?: number | null;
}
export type QueryMsg = {
  get_price: {
    key: string;
  };
} | {
  get_prices: {
    keys: string[];
  };
} | {
  get_config: {};
} | {
  get_rates: {};
};
export type Addr = string;
export interface CommonConfigResponse {
  config: CommonConfig;
  supported_keys: string[];
}
export interface CommonConfig {
  enabled: boolean;
  router: Contract;
}
export interface Contract {
  address: Addr;
  code_hash: string;
}
export type Uint256 = string;
export interface OraclePrice {
  data: ReferenceData;
  key: string;
}
export interface ReferenceData {
  last_updated_base: number;
  last_updated_quote: number;
  rate: Uint256;
}
export type ArrayOfOraclePrice = OraclePrice[];
export type ArrayOfRateData = RateData[];
export interface RateData {
  key: string;
  last_updated: number;
  max_change: Decimal256;
  permission: string;
  rate: Decimal256;
  timeout: number;
}