/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  router: RawContract;
}
export interface RawContract {
  address: string;
  code_hash: string;
}
export type ExecuteMsg = {
  set_pairs: RawPairData[];
} | {
  remove_pairs: string[];
} | {
  update_assets: RawAsset[];
} | {
  update_config: RawContract;
} | {
  set_status: boolean;
};
export interface RawPairData {
  base_token: RawAsset;
  key: string;
  pair: RawContract;
  target_token: RawAsset;
}
export interface RawAsset {
  contract: RawContract;
  quote_symbol: string;
}
export type QueryMsg = {
  get_price: {
    key: string;
  };
} | {
  get_prices: {
    keys: string[];
  };
} | {
  get_config: {};
} | {
  get_pairs: {};
};
export type Addr = string;
export interface CommonConfigResponse {
  config: CommonConfig;
  supported_keys: string[];
}
export interface CommonConfig {
  enabled: boolean;
  router: Contract;
}
export interface Contract {
  address: Addr;
  code_hash: string;
}
export type ArrayOfPairData = PairData[];
export interface PairData {
  base_token: Asset;
  key: string;
  pair: Contract;
  target_token: Asset;
}
export interface Asset {
  contract: Contract;
  decimals: number;
  quote_symbol: string;
}
export type Uint256 = string;
export interface OraclePrice {
  data: ReferenceData;
  key: string;
}
export interface ReferenceData {
  last_updated_base: number;
  last_updated_quote: number;
  rate: Uint256;
}
export type ArrayOfOraclePrice = OraclePrice[];