/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal256 = string;
export type Uint256 = string;
export type Uint64 = string;
export interface InstantiateMsg {
  basket: [string, Decimal256][];
  deviation_threshold: Decimal256;
  router: RawContract;
  symbol: string;
  target: Uint256;
  when_stale: Uint64;
}
export interface RawContract {
  address: string;
  code_hash: string;
}
export type ExecuteMsg = {
  compute_index: {};
} | {
  admin: AdminMsg;
};
export type AdminMsg = {
  update_status: ContractStatus;
} | {
  mod_basket: [string, Decimal256][];
} | {
  update_config: {
    deviation_threshold?: Decimal256 | null;
    router?: RawContract | null;
    symbol?: string | null;
    when_stale?: Uint64 | null;
  };
} | {
  update_target: Uint256;
} | {
  unfreeze_peg: {};
};
export type ContractStatus = "normal" | "deprecated" | "frozen";
export type QueryMsg = {
  get_price: {
    key: string;
  };
} | {
  get_prices: {
    keys: string[];
  };
} | {
  get_index_data: {};
} | {
  get_basket: {};
};
export interface BasketResponse {
  basket: [string, Decimal256, Decimal256][];
}
export type Addr = string;
export interface IndexDataResponse {
  basket: IndexAsset[];
  peg: Peg;
  router: Contract;
  symbol: string;
  when_stale: Uint64;
}
export interface IndexAsset {
  symbol: string;
  weight: AssetWeights;
}
export interface AssetWeights {
  fixed: Decimal256;
  initial: Decimal256;
}
export interface Peg {
  frozen: boolean;
  last_updated: Uint64;
  last_value: Uint256;
  target: Uint256;
  value: Uint256;
}
export interface Contract {
  address: Addr;
  code_hash: string;
}
export interface OraclePrice {
  data: ReferenceData;
  key: string;
}
export interface ReferenceData {
  last_updated_base: number;
  last_updated_quote: number;
  rate: Uint256;
}
export type ArrayOfOraclePrice = OraclePrice[];