[package]
name = "ensemble-tests"
version = "0.1.0"
authors = ["sbeem <sbeem@pm.me>", "scrtreddev <scrtredev@protonmail.com", "hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
  "cached_contracts",
]

[lib]
crate-type = ["cdylib", "rlib"]

[contract-helpers]
proc-macro = true

[features]
default = []

[dependencies]
colored = "2.0.0"
chrono = "0.4.19"
mulberry-utils = { version = "0.1.0", git = "git@github.com:securesecrets/shade-lend.git", branch = "develop", features = ["protocols"] }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.67"}
getrandom = { version = "0.2", features = ["js"] } # Prevents wasm from freaking out when running make
rand = { version = "0.8.4"}
shade-oracles = { path = "../shade_oracles" }

syn = { version="1.0.57",features=["full","fold"] }
quote = "1.0.8"

mock-band = { path = "../../contracts/mock_band" }
proxy-band-oracle = { path = "../../contracts/proxy_band_oracle" }
earn-v1-oracle = { path = "../../contracts/earn_v1_oracle" }
lp-oracle = { path = "../../contracts/lp_oracle" }
oracle-router = { path = "../../contracts/oracle_router" }
snip20 = { path = "../../contracts/snip20" }
